#!/bin/bash

export PRINTER="rfb-a241-2"
export LPDEST="rfb-a241-2"
source /opt/Xilinx/14.7/ISE_DS/settings64.sh &> /dev/null
export XILINX=/opt/Xilinx/14.7/ISE_DS/ISE
export PATH=${Xilinx}/bin/lin64:${Xilinx}/sysgen/util:${PATH}
